---
name: 'stackver'
description: 'Automated dependency version management'
inputs:
  stack:
    description: 'Stack file, relative to the repository root'
    required: true
  daysUntilDanger:
    description: 'Days until danger'
    required: false
    default: "30"
  daysUntilWarning:
    description: 'Days until warning'
    required: false
    default: "60"
  stackVerVersion:
    description: 'StackVer version'
    required: false
    default: "latest"
  githubToken:
    description: 'GitHub token for creating PRs'
    required: true
  dryRun:
    description: 'Only show what would be updated'
    required: false
    default: "false"
  prTitle:
    description: 'Pull request title'
    required: false
    default: "Update dependency versions"
  prBranch:
    description: 'Branch name for pull request'
    required: false
    default: "stackver/dependency-updates"
  baseBranch:
    description: 'Base branch to create PR against (defaults to repository default branch)'
    required: false

runs:
  using: "composite"
  steps:
    - name: Check Runner OS
      if: ${{ runner.os != 'Linux' }}
      shell: bash
      run: |
        echo "::error title=⛔ error hint::Support Linux Only"
        exit 1

    - name: Setup Git and GitHub CLI
      shell: bash
      run: |
        git config --global user.name "stackver[bot]"
        git config --global user.email "stackver[bot]@users.noreply.github.com"
        
        # Install GitHub CLI and jq if not present
        if ! command -v gh &> /dev/null; then
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh jq -y
        fi
        
        if ! command -v jq &> /dev/null; then
          sudo apt update && sudo apt install jq -y
        fi

    - name: Check for Updates (Dry Run)
      shell: bash
      env:
        STACKVER_VERSION: ${{ inputs.stackVerVersion }}
        STACK_FILE: ${{ inputs.stack }}
        DAYS_UNTIL_DANGER: ${{ inputs.daysUntilDanger }}
        DAYS_UNTIL_WARNING: ${{ inputs.daysUntilWarning }}
        GITHUB_TOKEN: ${{ inputs.githubToken }}
      run: |
        echo "::group::Checking for dependency updates"
        docker run --rm \
          -v ${PWD}:/stack \
          -w /stack \
          -e GITHUB_TOKEN=${GITHUB_TOKEN} \
          robertlestak/stackver:${STACKVER_VERSION} \
          -f ${STACK_FILE} \
          -d ${DAYS_UNTIL_DANGER} \
          -w ${DAYS_UNTIL_WARNING} \
          -dry-run
        echo "::endgroup::"

    - name: Check for Existing PR and Apply Updates
      if: ${{ inputs.dryRun != 'true' }}
      shell: bash
      env:
        STACKVER_VERSION: ${{ inputs.stackVerVersion }}
        STACK_FILE: ${{ inputs.stack }}
        DAYS_UNTIL_DANGER: ${{ inputs.daysUntilDanger }}
        DAYS_UNTIL_WARNING: ${{ inputs.daysUntilWarning }}
        GITHUB_TOKEN: ${{ inputs.githubToken }}
        PR_BRANCH: ${{ inputs.prBranch }}
        BASE_BRANCH: ${{ inputs.baseBranch }}
      run: |
        echo "::group::Checking for existing PR and applying updates"
        
        # Use provided base branch or detect default branch
        if [ -n "$BASE_BRANCH" ]; then
          DEFAULT_BRANCH="$BASE_BRANCH"
        else
          DEFAULT_BRANCH=$(git remote show origin | grep 'HEAD branch' | cut -d' ' -f5)
        fi
        echo "DEFAULT_BRANCH=${DEFAULT_BRANCH}" >> $GITHUB_ENV
        
        # Check if PR branch exists
        if git ls-remote --heads origin ${PR_BRANCH} | grep -q ${PR_BRANCH}; then
          echo "::notice::Found existing branch ${PR_BRANCH}, updating it"
          git fetch origin ${PR_BRANCH}
          git checkout ${PR_BRANCH}
          
          # Try to rebase, but don't fail if there are conflicts
          if ! git rebase origin/${DEFAULT_BRANCH}; then
            echo "::warning::Rebase failed, using existing branch as-is"
            git rebase --abort
          fi
          
          EXISTING_PR=$(gh pr list --head ${PR_BRANCH} --state open --json number | jq -r '.[0].number // empty')
          if [ -n "$EXISTING_PR" ]; then
            echo "EXISTING_PR_NUMBER=${EXISTING_PR}" >> $GITHUB_ENV
          fi
        else
          echo "::notice::Creating new branch ${PR_BRANCH}"
          git checkout -b ${PR_BRANCH}
        fi
        
        # Apply updates
        set +e
        UPDATE_OUTPUT=$(docker run --rm \
          -v ${PWD}:/stack \
          -w /stack \
          -e GITHUB_TOKEN=${GITHUB_TOKEN} \
          robertlestak/stackver:${STACKVER_VERSION} \
          -f ${STACK_FILE} \
          -d ${DAYS_UNTIL_DANGER} \
          -w ${DAYS_UNTIL_WARNING} \
          -update 2>&1)
        STACKVER_EXIT_CODE=$?
        set -e
        
        echo "$UPDATE_OUTPUT"
        
        if [ $STACKVER_EXIT_CODE -ne 0 ]; then
          echo "::error::Stackver failed with exit code $STACKVER_EXIT_CODE"
          exit $STACKVER_EXIT_CODE
        fi
        
        # Check if there are changes
        if git diff --quiet; then
          echo "::notice::No updates needed"
          echo "HAS_UPDATES=false" >> $GITHUB_ENV
          exit 0
        fi
        
        echo "HAS_UPDATES=true" >> $GITHUB_ENV
        
        # Extract updated dependencies
        UPDATED_DEPS=$(echo "$UPDATE_OUTPUT" | grep -E "(Successfully updated|Would update)" | sed -E 's/.*(Successfully updated|Would update) ([^:]+):.*/\2/' | sort -u | tr '\n' ',' | sed 's/,$//')
        echo "UPDATED_DEPS=${UPDATED_DEPS}" >> $GITHUB_ENV
        
        # Commit and push changes
        git add .
        git commit -m "Update dependency versions: ${UPDATED_DEPS}" || git commit --amend -m "Update dependency versions: ${UPDATED_DEPS}"
        git push origin ${PR_BRANCH} --force-with-lease
        
        echo "::endgroup::"

    - name: Create or Update Pull Request
      if: ${{ inputs.dryRun != 'true' && env.HAS_UPDATES == 'true' }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.githubToken }}
        PR_TITLE_BASE: ${{ inputs.prTitle }}
        PR_BRANCH: ${{ inputs.prBranch }}
      run: |
        echo "::group::Creating or updating pull request"
        
        # Generate PR title
        if [ -n "$UPDATED_DEPS" ]; then
          PR_TITLE="${PR_TITLE_BASE}: ${UPDATED_DEPS}"
        else
          PR_TITLE="${PR_TITLE_BASE}"
        fi
        
        # Truncate title if too long
        if [ ${#PR_TITLE} -gt 256 ]; then
          PR_TITLE="${PR_TITLE:0:253}..."
        fi
        
        # Generate PR body (single line to avoid YAML issues)
        PR_BODY="Automated dependency version updates by stackver. Updated dependencies: ${UPDATED_DEPS:-none}. This PR was created automatically by the stackver GitHub Action."
        
        # Update existing PR or create new one
        if [ -n "$EXISTING_PR_NUMBER" ]; then
          echo "::notice::Updating existing PR #${EXISTING_PR_NUMBER}"
          gh pr edit ${EXISTING_PR_NUMBER} --title "${PR_TITLE}" --body "${PR_BODY}"
        else
          echo "::notice::Creating new PR"
          gh pr create \
            --title "${PR_TITLE}" \
            --body "${PR_BODY}" \
            --head ${PR_BRANCH} \
            --base ${DEFAULT_BRANCH}
        fi
        
        echo "::endgroup::"
